[package]
name = "paramacode/watcher"
version = "0.1.4"
license = "MIT"
description = "A collection of observer classes for Roblox (Ancestry, Attribute, Children, Descendants, Property, Tag...)"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
